name = "UI Custom"
license = "MIT"
licenselink = "https://github.com/site-0003/ui-custom/blob/main/LICENSE"
description = "WebSite User Interface"
homepage = "https://metacraft.dev"
tags = ["website", "responsive", "multilingual", "mobile"]
features = ["posts", "shortcodes", "comments"]
min_version = "0.82.0"

[author]
  name = "MetaCraft Development"
  homepage = "https://metacraft.dev"
