name = "UI Custom"
license = "MIT"
licenselink = "https://github.com/site-0003/ui-custom/blob/main/LICENSE"
description = "WebSite User Interface"
homepage = "https://ihub.to"
tags = ["website", "responsive", "multilingual", "mobile"]
min_version = "0.82.0"

[author]
name = "iHub TO"
homepage = "https://ihub.to"
